### ISSUE TITLE
shared memory vs celery option

### ISSUE THREAD

**Issue by frankwiles** [frankwiles/django-app-metrics#19]
Create a way to store up metrics in shared memory and periodically flush them to the backend removing the need/overhead of celery for extremely high traffic sites.

**Comment by sks444** [comment]
@frankwiles, any progress on this?

**Comment by frankwiles** [comment]
No and honestly I doubt we get around to doing a shared memory option.  If anything we'd probably not do it in favor of having a Channels option. 

On a low traffic site you could install Celery, but set `CELERY_ALWAYS_EAGER = True` and have the same basic affect.
