### ISSUE TITLE
Celery is a big complex requirement if it's not needed

### ISSUE THREAD

**Issue by andybak** [frankwiles/django-app-metrics#41]
Installing celery (not especially a trivial task) if you don't need it seems especially onerous. I haven't examined the code but would conditional imports not remove the need for this?

(On a side note - there's often a simpler solution than Celery for many things it's used for - is this aspect of the code pluggable? A simple management command run via cron would be a good alternative for some)

**Comment by frankwiles** [comment]
Hi Andy, 

Sorry for the super delayed response.  Celery is definitely a hard requirement for this.  It's not an issue of running periodic tasks as much as the need to get the transmission of sending a metric out of the request/response cycle so taking metrics doesn't slow down the site itself.

**Comment by andybak** [comment]
Not running as part of the request/response cycle is a considerably simpler task than installing and maintaining Celery. At the most basic you can just use the subprocess module.

**Comment by frankwiles** [comment]
I think you are mistaken on the subprocess module, while that would put it into a different process it isn't down async but done entirely synchronously.  

If you aren't worried about the performance you can simply install Celery and set CELERY_ALWAYS_EAGER = True in production and it will run synchronously.
